name: "Android Gradle Plugin version finder"
description: "Find current stable and latest Android Gradle Plugin version for later use in Github Actions matrix"

inputs:
  debug:
    description: 'if true, shows additional debug information'
    required: false
    default: 'false'
  version-to-resolve:
    description: 'Has to be one of `stable`, `alpha`, `beta`, `rc`. Will be translated into specific version, available under `outputs.resolved-version`'
    required: false

outputs:
  latest-alpha:
    description: "Returns latest alpha AGP version"
    value: ${{ steps.run-action.outputs.latest-alpha }}
  latest-beta:
    description: "Returns latest beta AGP version"
    value: ${{ steps.run-action.outputs.latest-beta }}
  latest-rc:
    description: "Returns latest RC AGP version"
    value: ${{ steps.run-action.outputs.latest-rc }}
  latest-stable:
    description: "Returns latest stable AGP version"
    value: ${{ steps.run-action.outputs.latest-stable }}
  resolved-version:
    description: "Actual semver version resolved from `version-to-resolve`"
    value: ${{ steps.run-action.outputs.resolved-version }}

branding:
  color: 'green'
  icon: 'search'
runs:
  using: 'composite'
  steps:
    - id: run-action
      env:
        INPUT_DEBUG: ${{ inputs.debug }}
        INPUT_VERSION_TO_RESOLVE: ${{ inputs.version-to-resolve }}
      run: python3 '${{ github.action_path }}'/entrypoint.py
      shell: bash
