on:
  pull_request:

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    name: Run action
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - id: agp-version-finder
        uses: ./
        with:
          debug: true

      - uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: smoke-test

      - uses: peter-evans/create-or-update-comment@v3
        with:
          body: |
            ### smoke-test
            |channel|version|
            |---|---|
            |_stable_|`${{ steps.agp-version-finder.outputs.latest-stable }}`|
            |_rc_|`${{ steps.agp-version-finder.outputs.latest-rc }}`|
            |_beta_|`${{ steps.agp-version-finder.outputs.latest-beta }}`|
            |_alpha_|`${{ steps.agp-version-finder.outputs.latest-alpha }}`|
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
