on:
  pull_request:

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    name: Run action
    steps:
      - uses: actions/checkout@v5

      - id: agp-version-finder
        uses: ./
        with:
          debug: true
          version-to-resolve: 'stable'

      - uses: peter-evans/find-comment@v4
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: smoke-test

      - uses: peter-evans/create-or-update-comment@v5
        with:
          body: |
            ### smoke-test
            |channel|version|
            |---|---|
            |_stable_|`${{ steps.agp-version-finder.outputs.latest-stable }}`|
            |_rc_|`${{ steps.agp-version-finder.outputs.latest-rc }}`|
            |_beta_|`${{ steps.agp-version-finder.outputs.latest-beta }}`|
            |_alpha_|`${{ steps.agp-version-finder.outputs.latest-alpha }}`|
            |_resolved stable_|`${{ steps.agp-version-finder.outputs.resolved-version }}`|
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

  os-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: OS smoke test
    steps:
      - uses: actions/checkout@v5

      - id: agp-version-finder
        uses: ./

      - run: echo "${{join(steps.agp-version-finder.outputs.*, ' ')}}"
